### ISSUE TITLE
Upcoming release of TVDB API v3 & v4

### ISSUE THREAD

**Issue by KarellenX** [xbmc/repo-scrapers#116]
*Upcoming release of TVDB API v3 & v4 affecting metadata.tvdb.com Scraper *

### Add-on details:

- **General**
  - Add-on name: **The TVDB Scraper**
  - Add-on ID: **metadata.tvdb.com**
  - Version number: **3.0.15**
  - Kodi/repository version: 

- **Code location**
  - URL: 
  - Revision/tag: 
  - Branch:

### Description of changes:
TVDB have indicated that planned changes to the current API will occur on the 15 July 2019. Though they state backwards compatability for legacy systems, they also state no effort has been made to maintain regex based parsing. Previous experience shows changes at TVDB break our xml scrapers.

@ScudLee has not been seen since prior to Christmas, and not responded to a few pings I have sent in that time. I think it safe to assume that both our TV Show scrapers do not have a maintainer.

How will we deal with updating the current scrapers to their upcoming API v3 and, in the coming months, to API v4?
https://forums.thetvdb.com/viewtopic.php?f=118&t=56936&p=152480#p152427

TVDB Blog post describing some of the upcoming changes...
https://beta.thetvdb.com/blog/something_new

@olympia ^^

**Comment by olympia** [comment]
I can do some (most probably not everything) things for tmdb.
...not for tvdb as it uses XSLT

**Comment by sadsfae** [comment]
It seem like thetvdb has already some changes, tvdb scraping no longer works for me anymore on `metadata.tvdb.com` 3.0.15.  This is on 17.6 Krypton via Librelec 8.2.5.

I am experiencing the exact same issue as https://forum.kodi.tv/showthread.php?tid=329331&page=11

**Comment by thezoggy** [comment]
tvdb is aware, they have been having issues for a day+ now:
https://forums.thetvdb.com/viewtopic.php?f=118&p=155289#p155289

**Comment by thezoggy** [comment]
and now they are rolling back: https://forums.thetvdb.com/viewtopic.php?f=118&t=57711

**Comment by KarellenX** [comment]
The TVDB changes have come and gone (twice). 

There were issues with the TVDB updates and we have resolved what we could at our end, and the TVDB scraper is functional.

I think this issue can be closed.
