### ISSUE TITLE
bug in metadata.common.fanart.tv

### ISSUE THREAD

**Issue by taxigps** [xbmc/repo-scrapers#117]
https://github.com/xbmc/repo-scrapers/blob/529cc4d13b074eb4204ff52c5d4d6e5b6a4f877f/metadata.common.fanart.tv/fanarttv.xml#L692
this code can't get right strings. i think kodi don't replace $$18 to the language code before regular matching

https://github.com/xbmc/repo-scrapers/blob/529cc4d13b074eb4204ff52c5d4d6e5b6a4f877f/metadata.common.fanart.tv/fanarttv.xml#L698
there is not valid regular expression like !en

**Comment by pkscout** [comment]
The XML scrapers are mostly depreciated at this point, and this issue is three years old.  Any reason not to close it?
