### ISSUE TITLE
[TheMovieDB-TV Show] Not all actors are scraped

### ISSUE THREAD

**Issue by KarellenX** [xbmc/repo-scrapers#170]
The scraper does not download all actors when scraping some tv shows. This issue has been reported on the forum here... https://forum.kodi.tv/showthread.php?tid=200504&pid=2892747#pid2892747
I have also experienced this with a number of shows.

One show is **Marvel's Cloak & Dagger (2018)**
https://www.themoviedb.org/tv/66190-marvel-s-cloak-and-dagger?language=en-US
Out of the 19 main series actors, only the first 3 are scraped.

**Comment by ScudLee** [comment]
Should be fixed in v3.5.0.

The issue was that only the regular actors for the current season were part of the series details.
I fixed it by pulling the actors from each of the season pages instead.  Kodi seems to handle duplicate listings fine without the scraper having to worry about it.

**Comment by KarellenX** [comment]
Issue resolved with this PR... https://github.com/xbmc/repo-scrapers/pull/179
