### ISSUE TITLE
the movie database tv show 3.4.2 use the wrong api provided by https://www.themoviedb.org/

### ISSUE THREAD

**Issue by olinchy** [xbmc/repo-scrapers#178]
branch: leia
version: 3.4.2
file: repo-scrapers/metadata.tvshows.themoviedb.org/tmdb.xml
line: 5 
the api provided by themoviedb changed to https

an example: 

https://api.themoviedb.org/3/search/tv?api_key=6a5be4999abf74eba1f9a8311294c267&language=en&query=Arrow&first_air_date_year=2012

**Comment by KarellenX** [comment]
Fixed by @scudlee in #179
