### ISSUE TITLE
XBMC Gotham 13.2 failure to scrape

### ISSUE THREAD

**Issue by nousername8219** [xbmc/repo-scrapers#218]
Hey, 

My apologises for not following the proper guidelines but I don't know where else to ask. 

I've noticed 2 x machines running Gotham 13.2 are unable to scrape from TMDB. 

I've downloaded the repo and replaced all add-ons in appdata\roaming\xbmc\addons with the newly amended files from this fork to no avail. 

I see the latest amendment was under 3 weeks ago. Is this a known issue?

**Comment by KarellenX** [comment]
There was another report on the forum earlier today. Is this you also? https://forum.kodi.tv/showthread.php?tid=356651

I have a feeling there have been some changes at TheMovieDB, but there is nothing we can do until one of you provide a debug log. 

No-one on the team has v13, v14, v15 or v16 installed, so we will be relying on you to help track down the problem.

https://kodi.wiki/view/Log_file/Easy

**Comment by nousername8219** [comment]
Thanks so much for the quick update, appreciate it!

**Comment by KarellenX** [comment]
Gotham and Helix versions are too outdated to continue using TheMovieDB. 

No fix is available. Issue closed.

https://forum.kodi.tv/showthread.php?tid=356651&pid=2972712#pid2972712
