### ISSUE TITLE
[metadata.tvshows.themoviedb.org] Episode Titles not scraped with fallback language

### ISSUE THREAD

**Issue by KarellenX** [xbmc/repo-scrapers#225]
### Add-on details:
- **General**
  - Add-on name:  **The Movie Database** (tv shows)
  - Add-on ID: **[metadata.tvshows.themoviedb.org]**
  - Version number: **3.5.3**

### Issue Report
When the scraper is set to a language other than English, and the tv show does not have the selected translation, the scraper falls back to English. When this happens, episode titles are incorrectly scraped.

**Incorrectly scraped when scraper has fallen back to English**
https://api.themoviedb.org/3/tv/39775/season/1?api_key=f090bb54758cabf231fb605d3e3e0468&language=de-DE

![episode-titles](https://user-images.githubusercontent.com/44626605/95273178-17a50100-088e-11eb-8a74-d7cd6f2d951c.jpg)

**Correctly scraped when scraper is set to English**
https://api.themoviedb.org/3/tv/39775/season/1?api_key=f090bb54758cabf231fb605d3e3e0468&language=en-US

![episode-titles2](https://user-images.githubusercontent.com/44626605/95273283-63f04100-088e-11eb-8d3b-abbf54c682ce.jpg)

**Comment by KarellenX** [comment]
Turns out that this is a problem with TheMovieDb
![german](https://user-images.githubusercontent.com/44626605/95275175-8b95d800-0893-11eb-93e6-ee9892f26942.JPG)

**Comment by KarellenX** [comment]
Issue report here... https://www.themoviedb.org/talk/5f7d14070e597b0036b3d1ed

**Comment by hellcry37** [comment]
same for me

**Comment by razzeee** [comment]
@KarellenX can you follow up on this? can this be close, should we bug travis one more time?

**Comment by KarellenX** [comment]
Sorry @razzeee I completely missed your ping.

As far as I am aware, this is still an issue, and it also affects the python scraper by @pkscout 
There is another conversation at TMDB about it, but I can't seem to locate it. I know pkscout also responded in it, so he might be able to locate it. In short, TMDB are yet to implement fallback in their API.

**Comment by pkscout** [comment]
I'm going to go ahead and close this.  TMDb hasn't implemented the language fallback yet, but since we aren't really maintaining the XML scraper I don't think it makes any sense to leave an issue open for it.  I do periodically check to see if TMDb implemented language fallback, so maybe someday this will work the way we wish it would.
