### ISSUE TITLE
Themoviedatabase.org certprefix

### ISSUE THREAD

**Issue by Mister-XY** [xbmc/repo-scrapers#232]
### Add-on details:

- **General**
  - Add-on name: metadata.themoviedb.org
  - Add-on ID: metadata.themoviedb.org
  - Version number: 5.2.2
  - Kodi/repository version:
Hello, i have see that the certprefix/Rated have no translate. In german is not called Rated it called FSK.
Is it possible to add a string the translate it for the other languages?
In my case, i have change the line temporar in settings.xml from
    `<setting id="certprefix" default="true">Rated </setting>`
to
`<setting id="certprefix" default="true">FSK </setting>`
and now i have FSK  instead of Rated.
And i have see, that are more settings have no translation.

**Comment by KarellenX** [comment]
I am not sure how much luck you will have with the change. But if you use one of the other scrapers, there is a setting where you can enter the prefix you prefer.

Universal Movie Scraper has the cert prefix setting... https://kodi.wiki/view/Add-on:Universal_Movie_Scraper
The Movie Database Python also has this setting... https://kodi.wiki/view/Add-on:The_Movie_Database_Python

Both are available in the repo.

**Comment by Mister-XY** [comment]
I have also see, that i can change the prefix in themoviedatabse scraper for TVshows. Universal Movie Scraper is a nice scraper but have a small error with the movie family guy Something, Something, Something, Dark Side. It's use the IMDB TT instead the Movieid from TMDB and did not load the Movie Infos. So i must use TheMovieDatabase Scraper for the file.
The Movie Database Python load the english infos and covers for the Movies. But i have set all to German.

**Comment by KarellenX** [comment]
This is the last support you will receive here on Github. Any more questions, please ask them on the forum.


> It's use the IMDB TT instead the Movieid from TMDB and did not load the Movie Infos.

Sorry I don't know what you mean by this, and I cannot help without a debuglog

>The Movie Database Python load the english infos and covers for the Movies. But i have set all to German.

It works for me. There are no German posters, so of course you will get the English poster, but the info is all German for me.
Make sure you set the language in Videos>Files>YourSource>Context Menu>Change Content and **not** in the add-ons section.

![familyguy](https://user-images.githubusercontent.com/44626605/97913014-d0813180-1da1-11eb-8aee-dcfbf7295024.jpg)
