### ISSUE TITLE
[Broken] - metadata.filmaffinity.com

### ISSUE THREAD

**Issue by KarellenX** [xbmc/repo-scrapers#503]
**[Broken] metadata.filmaffinity.com-1.9.5**

### Add-on details:
- **General**
  - Add-on name: **metadata.filmaffinity.com**
  - Add-on ID: **metadata.filmaffinity.com**
  - Version number: **1.9.5**
  - Kodi/repository version:
- **Code location**
  - URL: **https://github.com/MaDDoGo/metadata.filmaffinity.com**
  - Revision/tag: 
  - Branch:

### Description of changes:
Scraper is broken and unmaintained. See screenshot here... https://github.com/MaDDoGo/metadata.filmaffinity.com/issues/79
I confirm the screenshot.

Please mark as broken in repo.

**Comment by romanvm** [comment]
Do you know in which branch this scraper is located?

**Comment by KarellenX** [comment]
It seems to be Gotham
https://github.com/xbmc/repo-scrapers/tree/gotham

**Comment by KarellenX** [comment]
Marked broken with this PR... https://github.com/xbmc/repo-scrapers/pull/520

**Comment by MaDDoGo** [comment]
Hey! I'm trying to fix the issues and re-enable the scrapper. How can this be done @KarellenX? Thanks!

**Comment by KarellenX** [comment]
@MaDDoGo 

You just need to update the scraper for v21 and resubmit to the repo.

But, it would be preferable that the scraper be upgraded to Python 3 as eventually XML scrapers will be deprecated. Not happening immediately, but sometime over the next couple of years.

**Comment by romanvm** [comment]
XML-based scrapers are basically deprecated, maybe not officially but de facto. So if this information provider is still relevant I'd recomment to create a Python-based scraper for it.

**Comment by MaDDoGo** [comment]
I was thinking on doing it in two steps:

- Reenable it with v1.9.9 release cut yesterday
- Work on the v2.0.0 based on py scrapping with a temporal solution (and a working addon)

Any guides on how to
- upgrade to v21
- migrate from XML to Py versions

Many thanks

**Comment by romanvm** [comment]
XML scrapers have always been an arcane art so I don't know much about them. As for Python scrapers, there are 2 articles in Kodi Wiki with general guidelines about them: https://kodi.wiki/view/Scrapers

And one of the advantages of Python scrapers is that you don't need to deal with regular expressions any more and can use proper HTML parsing libraries or JSON clients to retrieve information from websites or APIs.
