### ISSUE TITLE
[Broken] metadata.tvshows.themoviedb.org XML

### ISSUE THREAD

**Issue by KarellenX** [xbmc/repo-scrapers#514]
**Broken XML scraper - metadata.tvshows.themoviedb.org-3.5.xx**

This scraper has been broken for well over a year.

@olympia and I discussed the status of the XML scrapers at length and we agreed it best to remove the scraper from the repo as olympia did not have the time to maintain it anymore. The only scraper he is interested in maintaining  is UMS. It was also discussed that these XML scraper should be removed from Leia and later. This was done on 4 July 2022.

Krypton and earlier versions should still retain the scraper, otherwise those versions will no longer have a scraper, though I no longer agree with this as the scrapers are broken. No scraper, or broken scraper... no difference...

**The problem...**
Rather than marking the scraper as broken as is normal, olympia chose to delete the code in Leia scraper branch of Github.... https://github.com/xbmc/repo-scrapers/tree/leia

Unfortunately, this has left the scraper orphaned and still available in the repo for all branches from Leia to Nexus. (see links below)
Omega branch has an error and is making available a Gotham version of the scraper.

**The fix**
Delete the scraper from the mirrors. 
I don't remember who can do this. Is it @enen92 ?

### Add-on details:

- **General**
  - Add-on name: **metadata.tvshows.themoviedb.org**
  - Add-on ID:
  - Version number: **v3.5.xx**
  - Kodi/repository version:

- **Code location**
  - URL: https://mirrors.kodi.tv/addons/leia/metadata.tvshows.themoviedb.org/
  - https://mirrors.kodi.tv/addons/matrix/metadata.tvshows.themoviedb.org/
  - https://mirrors.kodi.tv/addons/nexus/metadata.tvshows.themoviedb.org/
  - https://mirrors.kodi.tv/addons/omega/metadata.tvshows.themoviedb.org/
  - Revision/tag: 
  - Branch:

### Checklist:

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-scrapers/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by enen92** [comment]
I don't have access to the mirrors, maybe @wsnipex or @ronie can do it

**Comment by romanvm** [comment]
I have created a PR to restore this addon in `leia` branch and mark it as broken: #515
