### ISSUE TITLE
Universal Movie Scraper Nexus 5.5.14: FILE SIZE BUG (to big: not recognition), small < 1 Gig recognised!

### ISSUE THREAD

**Issue by vigilant4u** [xbmc/repo-scrapers#526]
### Add-on details:

- **General**
  - Add-on name: Universal Movie Scraper Nexus 5.5.14
  - Add-on ID: 
  - Version number:  5.5.14
  - Kodi/repository version:NExus 20.2

- **Code location**
  - URL: 
 https://www.dropbox.com/scl/fi/4kom9b08nglfsv1u7yfdq/metadata.universal.zip?rlkey=u92t39ic8tut6tttc7vsd4v1y&dl=0

The BUG IS THE FOLLOWING: FILE SIZED BASED RECOGNITION OF MOVIES IN FLAT FOLDER STRUCTURE WEIRD BUT TRUE!

Universal Movie Scraper Nexus 5.5.14 stopped working reading /scraping the correct film names in a Flat Folder structure with not more than 400 movies correctly names like MOVIENAME (YEAR).mkv 
because og the FILE SIZE!
Yes you heard it right: The file Size.
So for example.
If i put in a fake file with around 1 GIg or less: The movie name is read correctly by Universal Movie Scraper Nexus 5.5.14
if i put in the real file with, let us say around 2.5 - 4 Gig in file size or even bigger it wont be recognized. Never! Even not manually.
The only workaround is sending the small size fake file on the server. Let it be recognized correctly and then overwrite it with the correct film and size (exact same name, as now it is already in the data base)

Please examine the bug the quickest possible with a proper workaround.
Thx
Vigilant

**Comment by KarellenX** [comment]
Need a debuglog that captures the problem.
FWIW, the file size plays no part in the scraping process.

**Comment by vigilant4u** [comment]
> Need a debuglog that captures the problem.
> FWIW, the file size plays no part in the scraping process. ==>
NOT TRUE. I CAN PROVE IT. WHAT DO YOU NEED? The Log?

**Comment by KarellenX** [comment]
>NOT TRUE. I CAN PROVE IT

Great. Then prove it.

>WHAT DO YOU NEED? The Log?

That is exactly what I asked for in my previous post...

**Comment by KarellenX** [comment]
No response from OP. Issue closed.
